services:
  db:
    image: postgres:16-alpine
    container_name: 3dprintinghub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: 3dprintinghub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapi:
    image: ghcr.io/alandelac/3d_printing_hub:latest
    container_name: mi-servicio
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=3dprintinghub_db;Username=admin;Password=${DB_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data: