# --- Etapa 1: Construir Angular con Node.js ---
FROM node:24-slim AS build
WORKDIR /app

# Copiar configuración de dependencias y descargarlas
COPY src/3DPrintingHub.Client/package*.json ./
RUN npm install

# Copiar el resto del código de Angular y compilar
COPY src/3DPrintingHub.Client/ ./
RUN npm run build --configuration=production

# --- Etapa 2: Servir con Nginx ---
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# Limpiar los archivos HTML por defecto de Nginx
RUN rm -rf ./*

# Angular 17+ genera el build en una subcarpeta 'browser'. La copiamos a Nginx
COPY --from=build /app/dist/frontend-app/browser .

# Copiar tu configuración de Nginx (proxy y rutas)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]