FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# Copiamos solo los archivos estáticos generados por Blazor
COPY publish-client/wwwroot .

# Copiamos la configuración de Nginx (para rutas de Blazor y proxy de API)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]