// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3DPrintingHub.Infrastructure.Data;

#nullable disable

namespace _3DPrintingHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804044244_EstructuraDeFilamentos")]
    partial class EstructuraDeFilamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.Filament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("BuyAgain")
                        .HasColumnType("boolean");

                    b.Property<string>("BuyLink")
                        .HasColumnType("text");

                    b.Property<Guid>("FilamentColorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilamentProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LastCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("RemainingWeightGrams")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilamentColorId");

                    b.HasIndex("FilamentProfileId");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.FilamentColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FilamentColors");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.FilamentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("IroningFlowPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("IroningSpeedMmS")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaterialTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SlopeAngleForSupports")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ZSeparationForSupports")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("FilamentProfiles");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.MaterialType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialType");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.ModelPrint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultSalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedWeightGrams")
                        .HasColumnType("integer");

                    b.Property<string>("FileLocationOrUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresIroning")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresSupports")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ModelPrints");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedMaterialCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FilamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelPrintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsedWeightGrams")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FilamentId");

                    b.HasIndex("ModelPrintId");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.ProductStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostToProduce")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModelPrintId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ModelPrintId");

                    b.ToTable("ProductStocks");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.Filament", b =>
                {
                    b.HasOne("_3DPrintingHub.Domain.Entities.FilamentColor", "Color")
                        .WithMany("Filaments")
                        .HasForeignKey("FilamentColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3DPrintingHub.Domain.Entities.FilamentProfile", "Profile")
                        .WithMany("Filaments")
                        .HasForeignKey("FilamentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.FilamentProfile", b =>
                {
                    b.HasOne("_3DPrintingHub.Domain.Entities.Brand", "BrandName")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintingHub.Domain.Entities.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandName");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.PrintJob", b =>
                {
                    b.HasOne("_3DPrintingHub.Domain.Entities.Filament", "Filament")
                        .WithMany()
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintingHub.Domain.Entities.ModelPrint", "ModelPrint")
                        .WithMany()
                        .HasForeignKey("ModelPrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");

                    b.Navigation("ModelPrint");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.ProductStock", b =>
                {
                    b.HasOne("_3DPrintingHub.Domain.Entities.ModelPrint", "ModelPrint")
                        .WithMany()
                        .HasForeignKey("ModelPrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelPrint");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.FilamentColor", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("_3DPrintingHub.Domain.Entities.FilamentProfile", b =>
                {
                    b.Navigation("Filaments");
                });
#pragma warning restore 612, 618
        }
    }
}
