name: Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Conectar el runner de GitHub a Tailscale para alcanzar la Raspberry Pi
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci # Requisito de Tailscale al usar OAuth para identificar el runner temporal

      - name: Copiar docker-compose al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.PI_USERNAME }}/3dprintinghub"

      - name: Desplegar en Raspberry Pi via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            # Moverse a la carpeta donde SCP dejó el archivo
            cd /home/${{ secrets.PI_USERNAME }}/3dprintinghub
            
            # 1. Crear el archivo .env inyectando el secreto de GitHub de forma segura
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            
            # 2. Iniciar sesión en GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            
            # 3. Descargar la imagen más reciente de tu API (.NET 10)
            docker compose pull webapi
            
            # 4. Levantar ambos contenedores (PostgreSQL y API)
            docker compose up -d
            
            # 5. Opcional: Limpiar imágenes viejas de Docker para no llenar la SD de la Raspberry
            docker image prune -af